const pathList = [
  { path: "/accordian", label: "Accordian" },
  { path: "/audioPlayer", label: "Audio Player" },
  { path: "/buttonRippleEffect", label: "Button Ripple Effect" },
  { path: "/clock", label: "Clock" },
  { path: "/currencyConverter", label: "Currency Converter" },
  { path: "/dragAndDrop", label: "Drag and Drop" },
  { path: "/expenceTracker", label: "Expense Tracker" },
  { path: "/folderTreeView", label: "Folder Tree View" },
  { path: "/imageSlider", label: "Image Slider" },
  { path: "/infiniteScroll", label: "Infinite Scroll" },
  { path: "/modal", label: "Modal" },
  { path: "/nestedComments", label: "Nested Comments" },
  { path: "/pagination", label: "Pagination" },
  { path: "/randomColor", label: "Random Color" },
  { path: "/scrollIndicator", label: "Scroll Indicator" },
  { path: "/scrollToSection", label: "Scroll To Section" },
  { path: "/searchAutocomplete", label: "Search Autocomplete" },
  { path: "/starRating", label: "Star Rating" },
  { path: "/stepProgressBar", label: "Step Progress Bar" },
  { path: "/ticTacToe", label: "Tic Tac Toe" },
  { path: "/toolTip", label: "Tool Tip" },
  { path: "/toggleTheme", label: "Toggle Theme" },
  { path: "/weather", label: "Weather App" },
  { path: "/quizApp", label: "Quiz App" },
];

export default pathList;
